# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ultra
tagline:          High-Performance UI Solution
url:              http://ultravg.github.io/ultra.vg/
paginate:         1
baseurl:          http://ultravg.github.io/ultra.vg/
author:
  name:           Adam Simmons
  url:            https://twitter.com/adamjsimmons
  email:          hi@adamjsimmons

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/UltraVG/ultra.vg
